### ISSUE TITLE
Bandcamp Changes

### ISSUE THREAD

**Issue by davetremblay** [cisoun/bandcamp-downloader#6]
Bandcamp made some changes regarding their page, and this program therefore doesn't work anymore. I don't know if there's an easy workaround, but it seems that some terms may need to be changed.

**Comment by cisoun** [comment]
Hey! Thanks for the notification.
No, I just took a look, it should be easy to adapt. Will do it if have some time this week.

**Comment by JDCourtney1969** [comment]
Hi.  I'm just a spectator here - a heavy user of Bandcamp who has used a couple of programs and web sites to convert many Bandcamp tracks to WAV files.   As of about a week ago, I am no longer able to produce large WAV files.   Someone told me it has something to do with "youtube-dl"...?   Is anyone else aware of this and has anyone tried to address this?   Either here, or in a different place (pull request?) on this site?   I am very new to this site and am having trouble navigating.  I'm just desperate to get this issue resolved.   Can anyone please help, or tell me where to go to find help?    Thank you!

**Comment by cisoun** [comment]
@JDCourtney1969 Hi and welcome!

First of all, unless you work for Bandcamp and know deeply their internal system, I doubt you were able to get real WAV files from them for free. Unless if you download free albums...

The tools (as this one) you use do in fact download the MP3 files stored in the Bandcamp pages. This is a simple operation as everyone can retrieve those MP3s by reading the HTML code of an album's page.

I guess the tools you've used converted them to WAV files, which is completely useless. Let me explain why: converting the MP3 to WAV will not only prevent you to have a high quality audio (as their MP3 are already compressed with a medium bitrate to 128 kbps) but will also take more space (as the WAV format is uncompressed). Maybe you already know that, if so, ignore my last statement. :)
My point is, just forget WAV files unless you buy/download an album directly from Bandcamp. You'll only end up with mediocre MP3 files disguised as WAV files.

I guess they might have changed a bit the structure of the HTML structure of their pages. Therefore, the current Bandcamp extractors will surely fail to find the MP3s through the page.

The solution here is to wait for an update of your tools.

I used to use mine way before I had a job, so these days, I just buy the albums and don't really use it anymore. I'll try to update it this week-end for the lulz anyway. :)

**Comment by cisoun** [comment]
Hi! I just wrote a new version of my script. It should do the job.
I'm open to feedbacks.

**Comment by davetremblay** [comment]
Hi, it seems that the "/" character still breaks the code when it's in the track title. Example:

https://neutralarchive.bandcamp.com/album/relax-magic

Thanks.

**Comment by cisoun** [comment]
@davetremblay: Should be fixed now.
