### ISSUE TITLE
Colon in the track name

### ISSUE THREAD

**Issue by Baladash** [cisoun/bandcamp-downloader#7]
Hello,

I noticed that a track with ":" in its name will not be downloaded properly.

The name will be stopped right before, example for a track named "abcd: efgh", only "abcd" will be copied and the file downloaded wil be empty.

Can it be fixed ?

Nice tool by the way,

Regards.

**Comment by cisoun** [comment]
Hi and thanks for the feedback!

Can you provide a Bandcamp page that I can try? Otherwise I'll find one myself.

**Comment by Baladash** [comment]
Sure,

https://gplowman.bandcamp.com/album/hp-lovecrafts-the-hound

**Comment by cisoun** [comment]
Thanks! It does actually work on a Mac (and I guess on Linux/BSD too). Are you on Windows?

Anyway, I've just pushed a fix. Could you try now?

**Comment by Baladash** [comment]
All right it is good now, thanks a lot for the quick fix ;)

**Comment by Baladash** [comment]
And yes I'm on Windows.

**Comment by Baladash** [comment]
In fact you just can't name a file with colon in it.

**Comment by cisoun** [comment]
Effectivement et je n'y avais pas pensé. Merci à toi! ;)

**Comment by Baladash** [comment]
Je t'en prie ^^
